# -*- coding: utf-8 -*-
"""NLP-Based Spam Message Detection Using TF-IDF and Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbakCyve7W_Kl5Kg3zjUKKEOmSEVhCrO

# MINI NLP PROJECT -
#Spam Message Detection Using NLP and Machine Learning

##Install libraries
"""

!pip install pandas numpy matplotlib seaborn scikit-learn nltk

"""##Import libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from collections import Counter

"""##Download NLTK resources"""

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

"""##Dataset

We will use the SMS Spam Collection dataset.

It contains SMS messages classified as:

* ham → normal message
* spam → unwanted/promotional/fraudulent message
"""

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

df = pd.read_csv(
    url,
    sep='\t',
    header=None,
    names=['label', 'message']
)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

df.head()

"""##Check dataset"""

print("Number of messages:", len(df))

print("\nDataset information:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nClass distribution:")
print(df['label'].value_counts())

"""##Visualize class distribution"""

plt.figure(figsize=(6, 4))

df['label'].value_counts().plot(
    kind='bar'
)

plt.title("Distribution of Ham and Spam Messages")
plt.xlabel("Message Type")
plt.ylabel("Number of Messages")
plt.xticks(rotation=0)

plt.show()

"""#NLP PREPROCESSING

##Define preprocessing function
"""

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # Tokenization
    words = word_tokenize(text)

    # Remove stopwords and short words
    words = [
        word for word in words
        if word not in stop_words and len(word) > 1
    ]

    return ' '.join(words)

"""##Apply preprocessing"""

df['clean_message'] = df['message'].apply(preprocess_text)

print("Original message:")
print(df['message'].iloc[0])

print("\nCleaned message:")
print(df['clean_message'].iloc[0])

"""##Display original and cleaned messages"""

df[['message', 'clean_message', 'label']].head(10)

"""#WORD FREQUENCY

##Find most common words
"""

all_words = ' '.join(df['clean_message']).split()

word_counts = Counter(all_words)

common_words = word_counts.most_common(15)

words = [item[0] for item in common_words]
counts = [item[1] for item in common_words]

plt.figure(figsize=(10, 5))

plt.bar(words, counts)

plt.title("Most Frequently Used Words")
plt.xlabel("Words")
plt.ylabel("Frequency")

plt.xticks(rotation=45)

plt.show()

"""#TRAIN / TEST SPLIT

##Prepare data
"""

X = df['clean_message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""#TF-IDF

##Convert text into numerical features
"""

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF training shape:", X_train_tfidf.shape)
print("TF-IDF testing shape:", X_test_tfidf.shape)

"""What this does?

The computer cannot directly understand sentences.

TF-IDF converts text into numerical values based on how important each word is within the messages.
"""

# We also use:
ngram_range=(1, 2)

"""which considers:

single words → unigrams
two-word combinations → bigrams

This can help identify phrases commonly associated with spam.

#MODEL 1 — NAIVE BAYES

##Train Naive Bayes
"""

nb_model = MultinomialNB()

nb_model.fit(
    X_train_tfidf,
    y_train
)

nb_predictions = nb_model.predict(X_test_tfidf)

print("Naive Bayes model trained successfully!")

"""##Evaluate Naive Bayes"""

nb_accuracy = accuracy_score(y_test, nb_predictions)
nb_precision = precision_score(
    y_test,
    nb_predictions,
    pos_label='spam'
)
nb_recall = recall_score(
    y_test,
    nb_predictions,
    pos_label='spam'
)
nb_f1 = f1_score(
    y_test,
    nb_predictions,
    pos_label='spam'
)

print("Naive Bayes Results")
print("-------------------------")
print("Accuracy :", round(nb_accuracy * 100, 2), "%")
print("Precision:", round(nb_precision * 100, 2), "%")
print("Recall   :", round(nb_recall * 100, 2), "%")
print("F1 Score :", round(nb_f1 * 100, 2), "%")

"""##Classification report"""

print("Classification Report - Naive Bayes")
print()

print(
    classification_report(
        y_test,
        nb_predictions
    )
)

"""##Naive Bayes confusion matrix"""

cm_nb = confusion_matrix(
    y_test,
    nb_predictions,
    labels=['ham', 'spam']
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm_nb,
    annot=True,
    fmt='d',
    xticklabels=['Ham', 'Spam'],
    yticklabels=['Ham', 'Spam']
)

plt.title("Naive Bayes Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""#MODEL 2 — LOGISTIC REGRESSION

##Train Logistic Regression
"""

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(
    X_train_tfidf,
    y_train
)

lr_predictions = lr_model.predict(X_test_tfidf)

print("Logistic Regression model trained successfully!")

"""##Evaluate Logistic Regression"""

lr_accuracy = accuracy_score(
    y_test,
    lr_predictions
)

lr_precision = precision_score(
    y_test,
    lr_predictions,
    pos_label='spam'
)

lr_recall = recall_score(
    y_test,
    lr_predictions,
    pos_label='spam'
)

lr_f1 = f1_score(
    y_test,
    lr_predictions,
    pos_label='spam'
)

print("Logistic Regression Results")
print("-------------------------")
print("Accuracy :", round(lr_accuracy * 100, 2), "%")
print("Precision:", round(lr_precision * 100, 2), "%")
print("Recall   :", round(lr_recall * 100, 2), "%")
print("F1 Score :", round(lr_f1 * 100, 2), "%")

"""##Classification report"""

print("Classification Report - Logistic Regression")
print()

print(
    classification_report(
        y_test,
        lr_predictions
    )
)

"""##Logistic Regression confusion matrix"""

cm_lr = confusion_matrix(
    y_test,
    lr_predictions,
    labels=['ham', 'spam']
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm_lr,
    annot=True,
    fmt='d',
    xticklabels=['Ham', 'Spam'],
    yticklabels=['Ham', 'Spam']
)

plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""#MODEL COMPARISON

##Compare models
"""

results = pd.DataFrame({
    'Model': [
        'Multinomial Naive Bayes',
        'Logistic Regression'
    ],

    'Accuracy': [
        nb_accuracy,
        lr_accuracy
    ],

    'Precision': [
        nb_precision,
        lr_precision
    ],

    'Recall': [
        nb_recall,
        lr_recall
    ],

    'F1 Score': [
        nb_f1,
        lr_f1
    ]
})

results

"""##Convert to percentage"""

results_percentage = results.copy()

results_percentage[
    ['Accuracy', 'Precision', 'Recall', 'F1 Score']
] = results_percentage[
    ['Accuracy', 'Precision', 'Recall', 'F1 Score']
] * 100

results_percentage

"""##Model comparison graph"""

metrics = [
    'Accuracy',
    'Precision',
    'Recall',
    'F1 Score'
]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(10, 6))

plt.bar(
    x - width/2,
    results_percentage.iloc[0][metrics],
    width,
    label='Naive Bayes'
)

plt.bar(
    x + width/2,
    results_percentage.iloc[1][metrics],
    width,
    label='Logistic Regression'
)

plt.xticks(x, metrics)

plt.ylabel("Percentage")
plt.xlabel("Evaluation Metrics")

plt.title("Comparison of NLP Classification Models")

plt.legend()

plt.ylim(0, 105)

plt.show()

"""#SAMPLE TESTING

##Test sample messages
"""

sample_messages = [
    "Congratulations! You have won a free lottery prize. Call now!",
    "Hey, are you coming to class tomorrow?",
    "URGENT! You have won 1000 dollars. Claim your prize now!",
    "Can you send me the notes from today's class?",
    "Get FREE entry into our competition. Text WIN to 80085!"
]

sample_clean = [
    preprocess_text(message)
    for message in sample_messages
]

sample_tfidf = tfidf.transform(sample_clean)

sample_predictions = nb_model.predict(sample_tfidf)

sample_results = pd.DataFrame({
    'Message': sample_messages,
    'Prediction': sample_predictions
})

sample_results

"""#USER INPUT SPAM DETECTOR

##Enter your own message
"""

def predict_spam(message):
    cleaned_message = preprocess_text(message)

    message_tfidf = tfidf.transform(
        [cleaned_message]
    )

    prediction = nb_model.predict(
        message_tfidf
    )[0]

    probability = nb_model.predict_proba(
        message_tfidf
    ).max()

    print("\nMessage:")
    print(message)

    print("\nPrediction:", prediction.upper())

    print(
        "Confidence:",
        round(probability * 100, 2),
        "%"
    )


user_message = input(
    "Enter a message to check whether it is Spam or Ham: "
)

predict_spam(user_message)

def predict_spam(message):
    cleaned_message = preprocess_text(message)

    message_tfidf = tfidf.transform(
        [cleaned_message]
    )

    prediction = nb_model.predict(
        message_tfidf
    )[0]

    probability = nb_model.predict_proba(
        message_tfidf
    ).max()

    print("\nMessage:")
    print(message)

    print("\nPrediction:", prediction.upper())

    print(
        "Confidence:",
        round(probability * 100, 2),
        "%"
    )


user_message = input(
    "Enter a message to check whether it is Spam or Ham: "
)

predict_spam(user_message)

"""#TEST BOTH MODELS

##Compare predictions
"""

def compare_models(message):
    cleaned_message = preprocess_text(message)

    message_tfidf = tfidf.transform(
        [cleaned_message]
    )

    nb_prediction = nb_model.predict(
        message_tfidf
    )[0]

    lr_prediction = lr_model.predict(
        message_tfidf
    )[0]

    print("\nMessage:")
    print(message)

    print("\nNaive Bayes Prediction:")
    print(nb_prediction.upper())

    print("\nLogistic Regression Prediction:")
    print(lr_prediction.upper())


user_message = input(
    "Enter a message for model comparison: "
)

compare_models(user_message)

"""#FINAL PROJECT SUMMARY"""

print("=" * 60)
print("       NLP-BASED SPAM MESSAGE DETECTION")
print("=" * 60)

print("\nDataset")
print("-------")
print("Total messages:", len(df))
print("Ham messages:", (df['label'] == 'ham').sum())
print("Spam messages:", (df['label'] == 'spam').sum())

print("\nNaive Bayes")
print("-----------")
print("Accuracy :", round(nb_accuracy * 100, 2), "%")
print("Precision:", round(nb_precision * 100, 2), "%")
print("Recall   :", round(nb_recall * 100, 2), "%")
print("F1 Score :", round(nb_f1 * 100, 2), "%")

print("\nLogistic Regression")
print("-------------------")
print("Accuracy :", round(lr_accuracy * 100, 2), "%")
print("Precision:", round(lr_precision * 100, 2), "%")
print("Recall   :", round(lr_recall * 100, 2), "%")
print("F1 Score :", round(lr_f1 * 100, 2), "%")

print("\nProject completed successfully!")